import "../styles/globals.css";
// import "../static/jank-empty.css";
import Head from "next/head";
import Layout from "../components/Layout";
// import "localstorage-polyfill";
import ToastContainer from "../components/ToastContainer";
import { useEffect } from "react";

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app">
        <ToastContainer />
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </main>
    </div>
  );
}

export default MyApp;
