import { TezosToolkit } from "@taquito/taquito";
import { BeaconWallet } from "@taquito/beacon-wallet";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import styled from "styled-components";

const Form = styled.div`
  color: red;
`;

export default function Home() {
  const Tezos = new TezosToolkit("https://mainnet-tezos.giganode.io");
  const wallet = new BeaconWallet({ name: "Beacon Docs Taquito" });
  const [address, setAddress] = useState();

  Tezos.setWalletProvider(wallet);

  const connectToWallet = async () => {
    try {
      console.log("Requesting permissions...");
      const permissions = await wallet.client.requestPermissions();
      setAddress(permissions.address);
      console.log("Got permissions:", permissions.address);
    } catch (error) {
      console.log("Got error:", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>MOONPRINT</main>
      {address ? (
        <div>{`Awesome, you are connected with wallet: ${address}`}</div>
      ) : (
        <button onClick={connectToWallet}>Connect Button</button>
      )}
      <Form>
        <h2>Styled component test</h2>
      </Form>
      <footer className={styles.footer}>
        <span>
          {`Made with <3 by Moonprint Team`}
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </span>
      </footer>
    </div>
  );
}
